<?php

declare(strict_types=1);

namespace Tests\Unit;

use Noxem\DateTime\DT as DateTime;
use Noxem\DateTime\Exception\BadFormatException;
use Tester\Assert;
use Tests\Fixtures\TestCase\AbstractTestCase;

require_once __DIR__ . '/../bootstrap.php';


/**
 * @testCase
 */
class AttributesTest extends AbstractTestCase
{
	public function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		date_default_timezone_set('Europe/Prague');
	}

	public function testConverts()
	{
		Assert::same(1654077600, DateTime::create(1654077600)->seconds());
		Assert::same(1654077600000, DateTime::create(1654077600)->msec());
		Assert::same(1654077600000000.0, DateTime::create(1654077600)->nano());
	}

	public function testInitializeByInput()
	{
		Assert::true(
			DateTime::create('2022-05-01 00:00:00')->areEquals(DateTime::createByMonth('2022-05'))
		);

		Assert::exception(
			fn() => DateTime::createByMonth('2022-foo'),
			BadFormatException::class
		);
	}
}

$test = new AttributesTest();
$test->run();