<?php

declare(strict_types=1);

namespace Tests\Unit;

use Noxem\DateTime\DateTimeImmutable as DateTime;
use Noxem\DateTime\Exception\BadFormatException;
use Noxem\DateTime\Term;
use Tester\Assert;
use Tests\Fixtures\TestCase\AbstractTestCase;

require_once __DIR__ . '/../bootstrap.php';


/**
 * @testCase
 */
class TermTest extends AbstractTestCase
{
	public function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		date_default_timezone_set('Europe/Prague');
	}

	public function testT()
	{
		$term = DateTime::create('2019-08-01 20:55:59')->term();
		Assert::type(Term::class, $term);
		Assert::same(1, $term->day());
		Assert::same(8, $term->month());
		Assert::same(2019, $term->year());
	}
}

$test = new TermTest();
$test->run();